"""create ticket tables

Revision ID: 55ee2375ea43
Revises: 
Create Date: 2026-09-06 15:46:15.186005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55ee2375ea43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('channel', sa.Enum('web', 'email', 'api', name='ticket_channel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', 'P4', name='ticket_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'awaiting_customer', 'resolved', 'escalated', name='ticket_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requester_role', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index('ix_tickets_status_priority', 'tickets', ['status', 'priority'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.Enum('customer', 'agent', 'human_support', 'system', name='message_author_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'ticket_id', name='uq_ticket_messages_id_ticket'),
    sa.UniqueConstraint('ticket_id', 'sequence_number', name='uq_ticket_messages_ticket_sequence')
    )
    op.create_table('processing_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('trigger_message_id', sa.UUID(), nullable=False),
    sa.Column('run_sequence', sa.Integer(), nullable=False),
    sa.Column('run_status', sa.Enum('running', 'completed', 'failed', name='processing_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('action', sa.Enum('resolve', 'ask_clarification', 'escalate', name='agent_action', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('final_reply', sa.Text(), nullable=True),
    sa.Column('extracted_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_version', sa.String(length=128), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("run_status != 'completed' OR action IS NOT NULL", name='ck_processing_results_completed_requires_action'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_processing_results_confidence_range'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['trigger_message_id', 'ticket_id'], ['ticket_messages.id', 'ticket_messages.ticket_id'], name='fk_processing_results_trigger_message_ticket'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'run_sequence', name='uq_processing_results_ticket_run_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_results')
    op.drop_table('ticket_messages')
    op.drop_index('ix_tickets_status_priority', table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
